### ISSUE TITLE
Loop: can't access or login to GRAO

### ISSUE THREAD

**Issue by jlandure** [Zenika/grao#55]
When I try to reach `https://grao.zenika.com/` I've blocked in a loop with some calls to `Auth0`.
=> `https://grao.zenika.com/#error=access_denied&error_description=Service%20not%20found%3A%20https%3A%2F%2Fgrao.zenika.com%2Fapi%2Fv1&state=i2PEBNDuzDMf7xVF9__Q0aJYxh~j5g6R`

**Comment by hgwood** [comment]
Grao is down while we upgrade the Dropbox interfacing to their v2 API. If you need to get it back up for any reason, you may use the GCP console.
